### ISSUE TITLE
Add a custom Dockerfile, preferably Alpine.

### ISSUE THREAD

**Issue by adityav-verma** [coderadi/flask-app#34]
**What?**
Add a custom Dockerfile, preferably Alpine.

**Why?**
- For better control on what all goes into the application
- For a lighter weight image

**Todo**
- [x] Discuss various methods to build images for Flask
- [ ] Document and finalize the flow
- [ ] Create an Alpine image
- [ ] Test
- [ ] Merge
